name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 'Breaking Changes'
    labels:
        - 'breaking change'
  - title: 'Enhancements'
    labels:
      - 'enhancement'
  - title: 'Bugs Fixed'
    labels:
      - 'bug'
  - title: 'Types'
    labels:
      - 'types'
  - title: 'Documentation'
    labels:
      - 'documentation'
  - title: 'Development'
    labels:
      - 'chore'
      - 'performance'
exclude-labels:
  - 'infrastructure'
change-template: '- #$NUMBER $TITLE'
change-title-escapes: '\<*_&`#@'
version-resolver:
  major:
    labels:
      - 'breaking change'
  minor:
    labels:
      - 'enhancement'
  patch:
    labels:
      - 'bug'
      - 'chore'
      - 'types'
  default: patch
template: |
  # Essential Links

  * [npm](https://www.npmjs.com/package/chartjs-plugin-annotation)

  $CHANGES

  Thanks to $CONTRIBUTORS
