name: documentation

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  checks:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: 16
      - name: Test Build
        run: |
          npm ci
          ./scripts/docs-config.sh master
          npm run docs
  gh-release:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: 16
      - name: Build
        run: |
          npm ci
          ./scripts/docs-config.sh master
          npm run docs
      - name: Release to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_AUTH_TOKEN }}
          publish_dir: dist/docs
          destination_dir: master
